version: "3.8"

services:
  bot:
    build: .
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env.prod
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
      - ./conf:/app/conf:ro # Read-only config
      - ./conf/ssl:/app/conf/ssl:ro # Read-only SSL certs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_READ_TIMEOUT=30
      - TELEGRAM_CONNECT_TIMEOUT=30
      - CONFIG_FILE=/app/conf/config.prod.json
      - ENVIRONMENT=production
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  bot_data:
  bot_logs:
